version: '3'

services:
  portfolio:
    container_name: portfolio
    hostname: portfolio
    image: nginx:latest
    healthcheck:
      test: "curl -f http://localhost"
      interval: "10s"
      timeout: "10s"
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: "./"
        target: "/usr/share/nginx/html"
